Division Tags
Denjell/TLE pull request #29
Opened 2023-09-03 21:19 UTC by andyluo03

2023-09-03 21:31 UTC, Denjell requested changes

2023-09-03 21:31 UTC, Denjell commented on tle/util/cache_system2.py
> +                    divisions.append(f'd{i}')
divX is enough

2023-09-03 21:31 UTC, Denjell commented on tle/util/cache_system2.py
> +                if f'div. {i}' in contest_name:
maybe we can increase the robustness if we steal some code from ;vc command
`        recommendations = {contest.id for contest in contests if
                           contest.matches(markers)`
where markers is like our tags. so we can just iterate over the 4 divisions and check 
`if contest_name.matches("div1") `
and ig it works

2023-09-03 21:31 UTC, Denjell commented on tle/util/cache_system2.py
> +                if f'div. {i}' in contest_name:
matches is a member function on the Contest object

2023-09-03 21:31 UTC, Denjell commented on tle/util/cache_system2.py
> +            contest_name = contest_name.lower()
not needed when using matches

2023-09-03 21:31 UTC, Denjell commented on tle/util/cache_system2.py
> +            for i in range(1, 5):
also use matches here, ig

2023-09-04 00:15 UTC, andyluo03 commented on tle/util/cache_system2.py
> +                    divisions.append(f'd{i}')
done

2023-09-04 00:16 UTC, andyluo03 commented on tle/util/cache_system2.py
> +            for i in range(1, 5):
done

2023-09-04 00:16 UTC, andyluo03 commented on tle/util/cache_system2.py
> +            contest_name = contest_name.lower()
done

2023-09-04 06:20 UTC, Denjell requested changes

2023-09-04 06:20 UTC, Denjell commented on tle/util/cache_system2.py
> +            for i in range(1, 5):
The code in both functions is doing the exact same, why is it so different :-). 
I also look for a more pythonic way to do it (for loops are for C++ devs :D)
Something like:
`divisions = [div_tag for div_tag in _DIV_TAGS if contest.matches(div_tag)]
 problem.tags.append(divisions)
`
And _DIV_TAGS can be declared globally for both functions.
` _DIV_TAGS = ['div1', 'div2', 'div3', 'div4']`

2023-09-04 06:20 UTC, Denjell commented on tle/util/cache_system2.py
> +            problem_contest: cf.Contest = self.cache_master.contest_cache.contest_by_id.get(problem.contestId)
I see why u use type hint but it does not really match the coding style used everywhere else. i would not start using it at single places.

2023-10-09 19:09 UTC, merged